export { isArray } from './isArray';
export { isDate } from './isDate';
export { isError } from './isError';
export { isMap } from './isMap';
export { isNull } from './isNull';
export { isNumber } from './isNumber';
export { isObject } from './isObject';
export { isSet } from './isSet';
export { isString } from './isString';
export { isWeakMap } from './isWeakMap';
export { isWeakSet } from './isWeakSet';
export { isSymbol } from './isSymbol';
export { isUndefined } from './isUndefined';
export { isBoolean } from './isBoolean';
export { isFunction } from './isFunction';
export { isArrowFunction } from './isArrowFunction';
export { isRegExp } from './isRegExp';
export { isPromise } from './isPromise';
export { isGeneratorFunction } from './isGeneratorFunction';
export { isAsyncFunction } from './isAsyncFunction';
export { isPrimitive } from './isPrimitive';
export { isInteger } from './isInteger';
export { isSafeInteger } from './isSafeInteger';
// export { isPlainObject } from './isPlainObject';
// export { isWindow } from './isWindow';
// export { isDocument } from './isDocument';
// export { isElement } from './isElement';
// export { isNodeList } from './isNodeList';
// export { isHTMLCollection } from './isHTMLCollection';
// export { isFile } from './isFile';
// export { isBlob } from './isBlob';
// export { isFormData } from './isFormData';
// export { isURLSearchParams } from './isURLSearchParams';
// export { isURL } from './isURL';
// export { isNativeError } from './isNativeError';
// export { isEvalError } from './isEvalError';

